name: Docker Build, Push, and Run

on:
  push:
    branches:
      - i200635

jobs:
  build-push-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker buildx create --use
        docker buildx build \
          --tag ${{ secrets.DOCKER_USERNAME }}/web_app:latest \
          .

    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/web_app:latest

    - name: Run Docker Container
      run: |
        docker run -d --name web_app_container -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/web_app:latest
